#%RAML 1.0
title: Inheritance Chain API

types:
  A:
    properties:
      a: string

  B:
    type: A
    properties:
      b: string

  C:
    type: B
    properties:
      c: string

  D:
    type: C
    properties:
      d: string