name: JetBrains Plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - 'external/raml-lsp-jetbrains/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'external/raml-lsp-jetbrains/**'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: gradle/actions/setup-gradle@v6
      with:
        cache-read-only: false

    - name: Build
      run: make build-plugin-jetbrains
